# PyTorch tensor cheatsheet

## Tensor creation / initialization

In [94]:
import torch
import numpy as np

In [95]:
# Empty tensor with 3 rows and 4 columns, initialized with random values taken from memory location where it is allocated.
torch.empty(3,4)

tensor([[2.6805e-34, 0.0000e+00, 3.2908e-34, 0.0000e+00],
        [4.4842e-44, 0.0000e+00, 8.9683e-44, 0.0000e+00],
        [3.2923e-34, 0.0000e+00, 1.4013e-44, 1.6255e-43]])

In [96]:
# Tensor of shape 5 rows and 6 columns filled up with zeroes
torch.zeros(5,6)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [97]:
# Three-dimensional tensor with 3 array, each of them containing two arrays and each of them containing 4 values
torch.rand(3,2,4)

tensor([[[0.5823, 0.3706, 0.9073, 0.0460],
         [0.4166, 0.0042, 0.2165, 0.0958]],

        [[0.6613, 0.8419, 0.7475, 0.2862],
         [0.1606, 0.7867, 0.3439, 0.4191]],

        [[0.4888, 0.3456, 0.3860, 0.8429],
         [0.2866, 0.2567, 0.3943, 0.7498]]])

In [98]:
# Array with only ones
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [99]:
print (torch.arange(5)) # Range starting from 0 (inclusive) up to 5 (exclusive)
print (torch.arange(1, 10, 2)) # Range starting from 1 (inclusive) up to 10 (exclusive) and with step 2

tensor([0, 1, 2, 3, 4])
tensor([1, 3, 5, 7, 9])


In [100]:
# 20 equally-spaced values starting from 0.1 up to 0.8
torch.linspace(start=0.1, end=0.8, steps=20)

tensor([0.1000, 0.1368, 0.1737, 0.2105, 0.2474, 0.2842, 0.3211, 0.3579, 0.3947,
        0.4316, 0.4684, 0.5053, 0.5421, 0.5789, 0.6158, 0.6526, 0.6895, 0.7263,
        0.7632, 0.8000])

In [101]:
# Samples from a normal distribution of mean 0 and variance 1
torch.normal(mean=0, std=1, size=(3,3))

tensor([[ 1.3028,  0.1192,  0.7775],
        [-0.2917,  2.0175,  0.6331],
        [-1.0684,  1.8255, -2.7504]])

In [102]:
# Create a tensor of size 3, containing only the number 4 and then use it as a diagonal of a matrix
x = torch.ones(3)*4
print (x)
print (torch.diag(x))

tensor([4., 4., 4.])
tensor([[4., 0., 0.],
        [0., 4., 0.],
        [0., 0., 4.]])


In [103]:
# Convert into different data types

x = torch.arange(10)
print ('Bool: ')
print (x.bool())

print ('Short: ')
print (x.short())

print ('Long: ')
print (x.long())

print ('Float: ')
print (x.float())

print ('Double: ')
print (x.double())

Bool: 
tensor([False,  True,  True,  True,  True,  True,  True,  True,  True,  True])
Short: 
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int16)
Long: 
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Float: 
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
Double: 
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)


## Convert between Numpy and Torch

In [104]:
np_array = np.zeros((3,3))
tensor = torch.tensor(np_array)
np_array_again = tensor.numpy()

## Tensor math

In [105]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

In [106]:
#  Addition
z1 = torch.empty(3)
torch.add(x, y, out=z1)
print (z1)
z2 = torch.add(x, y)
print (z2)

tensor([10., 10., 10.])
tensor([10, 10, 10])


In [107]:
x - y

tensor([-8, -6, -4])

In [108]:
torch.true_divide(x, y) # Element-wise division

tensor([0.1111, 0.2500, 0.4286])

In [109]:
x1 = torch.zeros(3)
t = torch.ones(3) * 9
print (t)
x1.add_(t)
x1

tensor([9., 9., 9.])


tensor([9., 9., 9.])

In [110]:
x1.pow(2)

tensor([81., 81., 81.])

In [111]:
x1**2

tensor([81., 81., 81.])

In [112]:
x1>0

tensor([True, True, True])

In [113]:
x1<0

tensor([False, False, False])

## Matrix multiplication

In [114]:
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
torch.mm(x1, x2) # New shape is (2,3)

tensor([[1.1030, 1.8213, 1.1683],
        [1.2544, 1.8047, 0.7151]])

In [115]:
x1.mm(x2)

tensor([[1.1030, 1.8213, 1.1683],
        [1.2544, 1.8047, 0.7151]])

In [116]:
m1 = torch.rand(2,2)
m1.matrix_power(4)

tensor([[0.8161, 0.6248],
        [0.8679, 0.6892]])

In [117]:
# Equivalent to m1.matrix_power(4)
m1.mm(m1.mm(m1.mm(m1)))

tensor([[0.8161, 0.6248],
        [0.8679, 0.6892]])

In [118]:
# Element-wise multiplication
m1*m1

tensor([[0.1973, 0.3736],
        [0.7207, 0.1024]])

In [121]:
print (x)
print (y)
print (x.dot(y)) # Equivalent to 1*9 + 2*8 + 3*7 = 46

tensor([1, 2, 3])
tensor([9, 8, 7])
tensor(46)


## Batch matrix multiplication

In [125]:
b=32
m=10
n=9
p=7
tensor1 = torch.rand((b,n,m))
tensor2 = torch.rand((b,m,p))
torch.bmm(tensor1, tensor2).shape # New shape: bxnxp

torch.Size([32, 9, 7])

## Broadcasting

In [139]:
x1 = torch.rand((1,5,5))
x2 = torch.rand((2,1,5))

In [140]:
x1-x2

tensor([[[-0.2675, -0.2314,  0.0805,  0.0796,  0.0539],
         [-0.0493, -0.7033, -0.4215,  0.2517,  0.1651],
         [-0.0872, -0.0309, -0.7419,  0.3631, -0.1257],
         [-0.6581, -0.0087, -0.7970, -0.2541, -0.7127],
         [-0.0335, -0.2447, -0.7296,  0.4055,  0.0095]],

        [[ 0.3297, -0.2918,  0.7825, -0.2712, -0.1162],
         [ 0.5479, -0.7637,  0.2805, -0.0991, -0.0051],
         [ 0.5100, -0.0914, -0.0399,  0.0122, -0.2958],
         [-0.0609, -0.0691, -0.0950, -0.6050, -0.8829],
         [ 0.5637, -0.3052, -0.0276,  0.0547, -0.1606]]])

In [141]:
x2-x1

tensor([[[ 0.2675,  0.2314, -0.0805, -0.0796, -0.0539],
         [ 0.0493,  0.7033,  0.4215, -0.2517, -0.1651],
         [ 0.0872,  0.0309,  0.7419, -0.3631,  0.1257],
         [ 0.6581,  0.0087,  0.7970,  0.2541,  0.7127],
         [ 0.0335,  0.2447,  0.7296, -0.4055, -0.0095]],

        [[-0.3297,  0.2918, -0.7825,  0.2712,  0.1162],
         [-0.5479,  0.7637, -0.2805,  0.0991,  0.0051],
         [-0.5100,  0.0914,  0.0399, -0.0122,  0.2958],
         [ 0.0609,  0.0691,  0.0950,  0.6050,  0.8829],
         [-0.5637,  0.3052,  0.0276, -0.0547,  0.1606]]])

In [151]:
values, indices = torch.max(x2, dim=0)
print (values.shape)
print (values)
print (indices)

torch.Size([1, 5])
tensor([[0.8888, 0.8930, 0.9034, 0.8210, 0.8907]])
tensor([[0, 1, 0, 1, 1]])


In [152]:
torch.mean(x1)

tensor(0.5756)

In [155]:
torch.eq(x1,x2) # Broadcasting also works in this case

tensor([[[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]],

        [[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]]])

In [161]:
sorted_x1, sorted_indices = torch.sort(x1, dim=1, descending=False)
print (x1.shape)
print (sorted_x1.shape)
print (sorted_x1)
print (sorted_indices)

torch.Size([1, 5, 5])
torch.Size([1, 5, 5])
tensor([[[0.2308, 0.1293, 0.1064, 0.2160, 0.0078],
         [0.6213, 0.5878, 0.1615, 0.5498, 0.5948],
         [0.8016, 0.6012, 0.1738, 0.7219, 0.7300],
         [0.8395, 0.8016, 0.4819, 0.8332, 0.7745],
         [0.8554, 0.8239, 0.9839, 0.8757, 0.8856]]])
tensor([[[3, 1, 3, 3, 3],
         [0, 4, 2, 0, 2],
         [2, 0, 4, 1, 4],
         [1, 2, 1, 2, 0],
         [4, 3, 0, 4, 1]]])


In [164]:
torch.clamp(x1, min=0, max=0.5) # All values less than 0 become 0 and all values bigger than 0.5 become 0.5

tensor([[[0.5000, 0.5000, 0.5000, 0.5000, 0.5000],
         [0.5000, 0.1293, 0.4819, 0.5000, 0.5000],
         [0.5000, 0.5000, 0.1615, 0.5000, 0.5000],
         [0.2308, 0.5000, 0.1064, 0.2160, 0.0078],
         [0.5000, 0.5000, 0.1738, 0.5000, 0.5000]]])

In [165]:
torch.any(x1>0.5)

tensor(True)

In [171]:
torch.all(x1>0.1)

tensor(False)

## Indexing

In [172]:
batch_size = 10
image_width = 8
image_height = 8
features = 12

x = torch.rand((batch_size, image_width, image_height, features))

In [177]:
x[0].shape # Each data item has shape 8x8x12

torch.Size([8, 8, 12])

In [182]:
x[:,0:3].shape # Take only the pixels along the width (vertical pixels) from position 0 to position 3 (excluded)

torch.Size([10, 3, 8, 12])

In [191]:
x[:,:,2:5,0:2].shape # Take all the batch size, then take all the width, but only the height pixels from position 2 to 5 (excluded), and for those, consider only the features between 0 and 2 (excluded)

torch.Size([10, 8, 3, 2])

In [192]:
x[...,0:3].shape # For every picture, take only the first 4 features

torch.Size([10, 8, 8, 3])

In [197]:
x = torch.arange(start=10,end=20,step=1)
indices = [2,5,8]
print(x[indices])

tensor([12, 15, 18])


In [207]:
x = torch.rand(3,7)
print (x)
rows = torch.tensor([0, 1])
cols = torch.tensor([0, 2])
print(x[rows,cols]) # Print element (0,0) and element (1,2)

tensor([[0.8544, 0.7617, 0.1113, 0.3726, 0.2284, 0.6990, 0.4754],
        [0.2534, 0.3926, 0.4926, 0.0138, 0.3614, 0.0068, 0.7978],
        [0.6152, 0.3663, 0.8777, 0.9007, 0.2058, 0.8745, 0.4386]])
tensor([0.8544, 0.4926])


In [208]:
# More advanced indexing
x = torch.arange(10)
print(x[(x < 2) | (x > 8)])  # will be [0, 1, 9]
print(x[x.remainder(2) == 0])  # will be [0, 2, 4, 6, 8]

tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])


In [209]:
# Useful operations for indexing
print(
    torch.where(x > 5, x, x * 2)
)  # gives [0, 2, 4, 6, 8, 10, 6, 7, 8, 9], all values x > 5 yield x, else x*2
x = torch.tensor([0, 0, 1, 2, 2, 3, 4]).unique()  # x = [0, 1, 2, 3, 4]
print(
    x.ndimension()
)  # The number of dimensions, in this case 1. if x.shape is 5x5x5 ndim would be 3
x = torch.arange(10)
print(
    x.numel()
)  # The number of elements in x (in this case it's trivial because it's just a vector)


tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
1
10


## Reshaping

In [215]:
batch_size = 10
image_width = 8
image_height = 8
features = 12

x = torch.rand((batch_size, image_width, image_height, features))
print(x.shape)

torch.Size([10, 8, 8, 12])


In [217]:
# You can reshape as long as the old array firs into the new dimension
x.reshape(image_width, image_height, batch_size, features).shape

torch.Size([8, 8, 10, 12])

In [220]:
print (x.shape)
print (torch.cat((x,x),dim=0).shape) # Concatenated along the first dimension, that is, double the batch size

torch.Size([10, 8, 8, 12])
torch.Size([20, 8, 8, 12])


In [222]:
print (x.shape)
print (torch.cat((x,x),dim=1).shape) # Concatenated along the first dimension, that is, double the image width

torch.Size([10, 8, 8, 12])
torch.Size([10, 16, 8, 12])


In [227]:
# Invalid operation! Because all the dimensions must match except for the one being concatenated

# x1 = torch.rand((batch_size, image_width, image_height, features))
# y1 = torch.rand((image_width, image_height, features, batch_size))
# torch.cat((x1,y1),dim=1)

In [244]:
# Change the dimensions positions
print(x.shape)
print(x.permute(0, 2, 3, 1).shape)

torch.Size([10, 8, 8, 12])
torch.Size([10, 8, 12, 8])


# Squeeze

In [254]:
x1 = torch.arange(10)
print(x1)
print(x1.shape)
print(x1.unsqueeze(0).shape)
print(x1.unsqueeze(0))
print(x1.unsqueeze(1).shape)
print(x1.unsqueeze(1))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([10])
torch.Size([1, 10])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([10, 1])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


In [265]:
x1 = torch.arange(10).unsqueeze(0)
print(x1)
print(x1.shape)
print(x1.squeeze(0).shape)
print(x1.squeeze(0))

print(x1.unsqueeze(-1).shape)
print(x1.unsqueeze(-1))

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 10])
torch.Size([10])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.Size([1, 10, 1])
tensor([[[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]])
